### ISSUE TITLE
button "Setup Names" in settings does not work

### ISSUE THREAD

**Issue by Lathelus** [reonZ/anonymous#26]
Hi, I've just installed the module for my DnD 5E campaign. The button in module's settings does not work, after clicking it an error appears in a console:
Error: An error occurred while rendering AnonymousNamesMenu 39. game.system.documentTypes.Actor.map is not a function
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5770:13
![image](https://github.com/reonZ/anonymous/assets/4583473/45badd71-0205-47af-a267-9c170cd5b902)

**Comment by reonZ** [comment]
The module hasn't be ported to v12 yet.
