### ISSUE TITLE
[1.6.1] -  Invalid escape [Detected 2 packages: anonymous(1.6.1), system:dnd5e(3.3.1)]

### ISSUE THREAD

**Issue by thatlonelybugbear** [reonZ/anonymous#32]
```js
foundry.js:655 
 Error: Error thrown in hooked function 'renderChatMessage' for hook 'dnd5e.renderChatMessage'. Invalid regular expression: /(^|\P{L})(Krusk|Krusk \(Half\-Orc Paladin\))(?=\P{L}|$)/gmu: Invalid escape
[Detected 2 packages: anonymous(1.6.1), system:dnd5e(3.3.1)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at ChatMessageMidi.getHTML (chat-message.mjs:94:11)
    at async ChatLog.updateMessage (foundry.js:89544:20)
Caused by: SyntaxError: Invalid regular expression: /(^|\P{L})(Krusk|Krusk \(Half\-Orc Paladin\))(?=\P{L}|$)/gmu: Invalid escape (at chat.js:48:20)
[Detected 2 packages: anonymous(1.6.1), system:dnd5e(3.3.1)]
```

Seems like JS doesn't directly support something like `\P{...}`

Maybe, 
```js
const regexp = new RegExp(`(^|[^\\p{L}])(${joined})(?=[^\\p{L}]|$)`, "gmu");
```

**Comment by reonZ** [comment]
weird, i have tested the PR before pushing it.

**Comment by thatlonelybugbear** [comment]
Hmmm if you cannot reproduce with the Krusk (Half-Orc) Barbarian from the SRD Heroes, it might be something specific to my instance (modules etc).

![image](https://github.com/user-attachments/assets/1cd08adf-e56a-4432-9242-c2267bcac2b2)
